"""add anushka models

Revision ID: 3814d90b8121
Revises: e2f3a4b5c6d7
Create Date: 2026-04-26 19:02:37.035863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3814d90b8121'
down_revision = 'd1c4ccdbd468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anushka_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('track', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('mastery_threshold', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anushka_question_banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('track', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anushka_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('topic_name', sa.String(length=255), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('final_text', sa.Text(), nullable=True),
    sa.Column('ai_score', sa.Float(), nullable=True),
    sa.Column('ai_flagged', sa.Boolean(), nullable=True),
    sa.Column('teacher_score', sa.Integer(), nullable=True),
    sa.Column('scored_by', sa.String(length=36), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scored_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['anushka_topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anushka_topic_prerequisites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prerequisite_id'], ['anushka_topics.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['anushka_topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'prerequisite_id')
    )
    op.create_table('anushka_user_topic_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('quiz_score', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['anushka_topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'topic_id')
    )
    op.create_table('courses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('topic_keyword', sa.String(length=100), nullable=True),
    sa.Column('instructor_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('anushka_edit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('text_snapshot', sa.Text(), nullable=False),
    sa.Column('chars_added', sa.Integer(), nullable=False),
    sa.Column('chars_removed', sa.Integer(), nullable=False),
    sa.Column('is_paste', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['anushka_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anushka_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('q_type', sa.String(length=20), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct', sa.String(length=255), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['anushka_question_banks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_enrollments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'student_id')
    )
    op.create_table('assignment_groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assignment_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=True),
    sa.Column('assignment_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('log_type', sa.String(length=20), nullable=True),
    sa.Column('logged_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('time_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_logs_user_id'), ['user_id'], unique=False)

    op.create_table('group_memberships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['assignment_groups.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'student_id')
    )
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_group', sa.Boolean(), nullable=True))

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(None, 'assignment_groups', ['group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('group_id')

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_column('is_group')

    op.drop_table('group_memberships')
    with op.batch_alter_table('time_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_logs_user_id'))

    op.drop_table('time_logs')
    op.drop_table('assignment_groups')
    op.drop_table('course_enrollments')
    op.drop_table('anushka_questions')
    op.drop_table('anushka_edit_events')
    op.drop_table('courses')
    op.drop_table('anushka_user_topic_progress')
    op.drop_table('anushka_topic_prerequisites')
    op.drop_table('anushka_submissions')
    op.drop_table('anushka_question_banks')
    op.drop_table('anushka_topics')
    # ### end Alembic commands ###
