"""remove focus_sessions table

Revision ID: 54e399c299dd
Revises: af14c5d9d1e1
Create Date: 2026-08-06 18:12:31.331740

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '54e399c299dd'
down_revision = 'af14c5d9d1e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('focus_sessions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('focus_sessions',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('topic_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('topic_label', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sessions_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('focus_sessions_topic_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('focus_sessions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('focus_sessions_pkey'))
    )
    # ### end Alembic commands ###
