"""add learning_profiles table

Revision ID: 76e3adada0b9
Revises: bf1851629b69
Create Date: 2026-08-06 20:23:57.864165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76e3adada0b9'
down_revision = 'bf1851629b69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.Column('forgetting_patterns', sa.JSON(), nullable=True),
    sa.Column('revision_needed', sa.JSON(), nullable=True),
    sa.Column('learning_style', sa.String(length=50), nullable=True),
    sa.Column('learning_style_note', sa.Text(), nullable=True),
    sa.Column('pace', sa.String(length=20), nullable=True),
    sa.Column('confidence_level', sa.String(length=20), nullable=True),
    sa.Column('best_study_times', sa.JSON(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_recommendations', sa.JSON(), nullable=True),
    sa.Column('data_points', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learning_profiles')
    # ### end Alembic commands ###
