"""add course status and question bank course_id

Revision ID: af14c5d9d1e1
Revises: f1a2b3c4d5e6
Create Date: 2026-08-06 16:43:50.871319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af14c5d9d1e1'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anushka_question_banks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['id'])

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='active'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('anushka_question_banks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###
