"""add course_id to resources, make topic_id nullable

Revision ID: ee743970e57c
Revises: 76e3adada0b9
Create Date: 2026-08-06 22:18:05.718582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee743970e57c'
down_revision = '76e3adada0b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('file_name', sa.String(length=255), nullable=True))
        batch_op.alter_column('topic_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('topic_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_column('file_name')
        batch_op.drop_column('description')
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###
